name: Deploy to Azure Static Web Apps

on:
  workflow_call:
    inputs:
      branch:
        description: The branch to deploy from
        required: true
        type: string
      deployment_environment:
        description: The environment to deploy to or empty for the production environment
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web Apps
    steps:
      - name: Checkout the deployment branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          deployment_environment: ${{ inputs.deployment_environment }}
          skip_app_build: true
          app_location: "/"
          api_location: ""
          output_location: "/"
